### ISSUE TITLE
没找到lightsocks_local.jar文件

### ISSUE THREAD

**Issue by luckypoem** [XUranus/lightsocks-java#1]
hi。

yudeMacBook-Air:lightsocks-java-by-XUranus brite$ ls
README.md		localConfig.json	src
lib			out
lightsocks-java.iml	serverConfig.json
yudeMacBook-Air:lightsocks-java-by-XUranus brite$ find . -name lightsocks_local.jar
yudeMacBook-Air:lightsocks-java-by-XUranus brite$

谢谢回复

**Comment by luckypoem** [comment]
可否提供pom.xml文件？这样方便用户自己运行mvn package,来生成lightsocks_local.jar和
lightsocks_server.jar文件

**Comment by XUranus** [comment]
已改为maven项目

**Comment by luckypoem** [comment]
hi.

root@racknerd-7b97d8 lightsocks-java-by-XUranus]# mvn package -Dmaven.test.skip=true
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< com.xuranus:lightsocks-java >---------------------
[INFO] Building lightsocks-java 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ lightsocks-java ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /root/lightsocks-java-by-XUranus/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ lightsocks-java ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 18 source files to /root/lightsocks-java-by-XUranus/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Failure executing javac, but could not parse the error:
javac: invalid target release: 9
Usage: javac <options> <source files>
use -help for a list of possible options

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.956 s
[INFO] Finished at: 2021-05-04T12:44:39-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project lightsocks-java: Compilation failure
[ERROR] Failure executing javac, but could not parse the error:
[ERROR] javac: invalid target release: 9
[ERROR] Usage: javac <options> <source files>
[ERROR] use -help for a list of possible options
[ERROR] 
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[root@racknerd-7b97d8 lightsocks-java-by-XUranus]#

how to fix it?
